os: linux
sudo: required
language: "minimal"
services:
  - docker
env:
  - DOCKER_IMAGE="toliak/bootstrap-cpp"

before_script:
  - docker pull $DOCKER_IMAGE

jobs:
  include:
    - name: "checks"
    script:
    - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh

notifications:
  email: false
